CREATE TABLE "DRAGON" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "NAME" VARCHAR(255) NOT NULL,
    "ELEMENT" VARCHAR(42) NOT NULL,
    "SPEED" INT NOT NULL,
    "BORN" DATE NOT NULL
);

CREATE TABLE "PERSON" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "NAME" VARCHAR(255) NOT NULL,
    "SURNAME" VARCHAR(255) NOT NULL,
    "EMAIL" VARCHAR(255) NOT NULL
);

CREATE TABLE "RESERVATION" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "TIMEFROM" TIMESTAMP NOT NULL,
    "TIMETO" TIMESTAMP,
    "BORROWER" BIGINT NOT NULL,
    "DRAGON" BIGINT NOT NULL,
    "MONEYPAID" DECIMAL NOT NULL,
    "PRICEPERHOUR" DECIMAL NOT NULL
);
